pub mod bootstrap;
pub mod commands;
pub mod connection;
pub mod cron_runs;
pub mod env_file;
pub mod environment;
pub mod error;
pub mod oauth_session;
pub mod path_resolver;
pub mod session_archive;
pub mod session_log;
pub mod state;
pub mod ui_store;
pub mod util;

#[cfg(feature = "desktop")]
pub mod coding_agents;
#[cfg(feature = "desktop")]
pub mod desktop_control;
#[cfg(feature = "desktop")]
pub mod prevent_sleep;
#[cfg(feature = "desktop")]
pub mod process;
#[cfg(feature = "desktop")]
pub mod supervisor;
#[cfg(feature = "desktop")]
pub mod tray;
#[cfg(feature = "desktop")]
pub mod update_stage;
