// Hermes Agent Mobile — binary entry point.
//
// Desktop builds call into the library's run(); Android builds ignore this
// binary entirely and load libhermes_agent_cn.so via the JNI entry point
// generated by tauri::mobile_entry_point in lib.rs.

#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

fn main() {
    hermes_agent_cn::run()
}
